name: react C/CD
on:
  push:
    branches:
    -  "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: action/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test